apiVersion: apps/v1
kind: Deployment
metadata:
  name: r-api-1-1
  namespace: ons-data-explorer
  labels:
    app: climate-health-r-api-1-1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: climate-health-r-api-1-1
  template:
    metadata:
      labels:
        app: climate-health-r-api-1-1
    spec:
      containers:
        - name: r-api-1-1
          image: 142496269814.dkr.ecr.us-west-2.amazonaws.com/ons-climate-health/climatehealth:1.1.5
          ports:
            - containerPort: 8000
