version: "3.8"

services:
  web:
    build:
      dockerfile: data-explorer.Dockerfile
      context: .
    ports:
      - "5000:5001"
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
      # - migration
    environment:
      - FLASK_ENV=development
      - FLASK_APP=data_explorer
      # - FLASK_APP=app.py
      - LOAD_DUMMY_DATA=True

  db:
    image: postgres:16
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=data-explorer-db
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432

  # migration:
  #   image: postgres:13 # or a custom image if required
  #   volumes:
  #     - ./migrations:/migrations
  #   ports:
  #     - 5432:5432
  #   depends_on:
  #     - db
  #   environment:
  #     - POSTGRES_HOST=db
  #     - POSTGRES_DB=data-explorer-db
  #     - POSTGRES_USER=myuser
  #     - POSTGRES_PASSWORD=mypassword
  #   command: >
  #     bash -c "
  #     until pg_isready -h $$POSTGRES_HOST; do
  #       echo 'Waiting for DB';
  #       sleep 2;
  #     done;
  #     psql -h db -U myuser -d data-explorer-db -f /migrations/01-initial-migrations.sql;
  #     "
  #   restart: on-failure

volumes:
  postgres_data:
