apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJWDV4T0xFa0c2a2t3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TXpBNU1qSXdNREl4TWpoYUZ3MHpNekE1TVRrd01ESXhNamhhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUM2cTd3d203Q1R4b28xZDV3bnFtck9DakVjdlFFVVlQS0tQUGdDNG1ITFdnK0daR1ZCVlBiUW1TNVYKVk8zb1RxUCs1VXpGdUl6eDBRbEhQdTNaRU84dXBMNHJDUVVhV0lFZTBrZzdCMklXQ0diSmErYXNUZ040SXFmcwpDd05yOXhnZ1RLaWN0RjBpZ2VPR2pjaVlURUlscHBlNkZJQ2RIc2RoTmVoZG1vRHdjc1VGeUltUXdRemFYeEZhCkwrZ0FLNTJXVGF3YkR1NklnN09Tamh4QnVWY1VrR0hCdWdmRXVXWCtZYnVMcVM5b1J2N0ZwTGVwQmsxOWdXVTMKMk9TQ2ZBMThyM3lKVmY1N2J0TUJIaTgxajAwQ3lKdmVlSzRvbWNTNklHK3NTb2djWmFOY1lRVzVZd0RIeC9pRApHb281K2NBWEVVVjQzb01xR1BDZFMrYnlLdlVyQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJRZFRvb2JQMmRTdlFaUWplRjlQYi9IMndubWN6QVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQVUySTV2SlBmKwp0MjJ5b2IyNFA4R2VNdDBxdHc5ZW16Mm9ya3FDMUlPRDF3OHFUSENqMTN3RlFHYjN6dGJNVVRsNHRLYWlNOHYvCmFicE1Db2hFRWlpK1VqNEdQbkczTEFKaW5KSVA1TmlJZXpyVnhXQStxVW0vOSt6cGdvVlREK0d4aVYzLzB2MncKbDFMN1poRTZvYzNiUEh2aFFtT3NRaUtTMFE2Mi9iMFpVeUdlcnBaMWNZUUZXTnZjWGFlR0FzelB1Um0wNmk3cApwMk5RLzNmaVJGcGoxOXFKK1JrQ2VpMk1OdHRXTk1XbzZBNG1wZHhFbVJTeXp2TGZjWGNNY0J0YVR5UEh6M09yCk5EVElBN0F5d2FrTzh2ZkVUUnRMWVJsNXBKM1QweWxuays5VjJram9Ia0F0MWllOXdkMEtUOUg1ekhUbmtmb1oKZ1hCTG9sL1ptQzVhCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://8F491AA54197911A1CB5637DC434A57C.sk1.us-west-2.eks.amazonaws.com
  name: arn:aws:eks:us-west-2:142496269814:cluster/dev-cluster
contexts:
- context:
    cluster: arn:aws:eks:us-west-2:142496269814:cluster/dev-cluster
    user: codepipeline
  name: arn:aws:eks:us-west-2:142496269814:cluster/dev-cluster
current-context: arn:aws:eks:us-west-2:142496269814:cluster/dev-cluster
kind: Config
preferences: {}
users:
- name: arn:aws:eks:us-west-2:142496269814:cluster/dev-cluster
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - us-west-2
      - eks
      - get-token
      - --cluster-name
      - dev-cluster
      - --output
      - json
      command: aws
      env:
      - name: AWS_PROFILE
        value: AdministratorAccess-142496269814
      interactiveMode: IfAvailable
      provideClusterInfo: false
- name: codepipeline
  user:
    token: k8s-aws-v1.aHR0cHM6Ly9zdHMudXMtd2VzdC0yLmFtYXpvbmF3cy5jb20vP0FjdGlvbj1HZXRDYWxsZXJJZGVudGl0eSZWZXJzaW9uPTIwMTEtMDYtMTUmWC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BU0lBU0NMTFFRWDNNRUJLRFU0WCUyRjIwMjQwMTE4JTJGdXMtd2VzdC0yJTJGc3RzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMThUMTQxNTA0WiZYLUFtei1FeHBpcmVzPTYwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCUzQngtazhzLWF3cy1pZCZYLUFtei1TZWN1cml0eS1Ub2tlbj1JUW9KYjNKcFoybHVYMlZqRUM0YUNXVjFMWGRsYzNRdE1TSkdNRVFDSUF5RlpSZnlVRjlFS2RKWGUlMkZibERaR0NVZXRNc0lLRTZXR1l2TzllVHRZdEFpQiUyRkM5SXIlMkJBU0pKN0RVeHFZOUE2c0JPRmtuME03WFUyT2ZMJTJGZUNlTlhiV2lxUEF3alglMkYlMkYlMkYlMkYlMkYlMkYlMkYlMkYlMkYlMkY4QkVBUWFEREUwTWpRNU5qSTJPVGd4TkNJTWlEb044MHE0V0RoaUlBYUdLdU1DWWROcXhtS242VXNJN3pQWjhKN2tJeFIwOGxSZCUyQlRGZnlSMWZqdnhhY0d1MFJ6b0ZkQm83TGc1T1pYWTVsVGloM2lkR2VHemphNVUyUm5PZDJhZ3doVTlxTXZzQkQ3NE1leCUyQnBRdUdpeGNXNmFYNCUyRlBMN2IwY1AwTFBzYVFaSTFGOHRkcm5DbTZUbW5tSmgzVXBVVHE3VkxkUGJzcVRoU1MyN0xCb1IydElTNXFmQlNVR1RFanIzT1JHc0VxRFRIczZzamoxQURuSWxvNEVETzJGd0UxcXhKUVVqSVpnJTJGM1QlMkJQbDhPdEF4c2pXVlo3cFdtZmVDdnZoRndZS1gwQm54bVpjbGZoWUd3RWs1ZEx5blRLTERlczZQRHNqUVJRSEJLbnhsdnhla2ZkU2RYQ212dmslMkIlMkJaVkMzYmI5bndKVGRndFdOS1k5MmFCd2NJNExPbGFaJTJGQUlOakx4RUNZeFU5UnolMkJlOVBBeGJBNzFndmYzQ1BNekdhWmFWZkROWDA0bTFpcjd1YzhQWUNIMXFRZEpnckJGYmUlMkZFclEzN1l5WEVEY0NTSDA1R0p1cWRFSVVhMVd3Y3ptWmFzTnoxQ2lBaER4NlFpdHE0ZTFwRWw4MjRnSEpRUUtpNWpEbTRhU3RCanFuQVROSzc5JTJGVFJGa2FRQmlNVGI1R1V2YkVWakgxUmNYakp1TktjY2dhM0ZWZEF6MjdKQTYwbHpZUzlCbjlndEVXbGxqWVc1Y29TTUI4OGRBQnBiaTJKOTFFN0J1YjNRM2N6JTJGdTAlMkJQTmZURCUyRlRyV2k3MlB3VHRhaFVhRlFpWFNIVXVCVzM4WmZQa2lqMU1vM1NSc090JTJCNDdrMm5WRUZubkJKa2loVTRGWG05RXoyd3JQSEFiaE9HUDFnUEVMWEFNT29xZ1FuR1dkMjNUSDdKZ2huVUdacFRtYzU0RXh6ekt1JlgtQW16LVNpZ25hdHVyZT01Y2U3NThjMDgxZGY3MDM2ZWE3M2RiNDE4ZTdjNmMxYTE2ZGEzYWE0NTQxZTRhNWM2NWEwNDI3M2RkYzlhY2Q3
