apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRES_DB: flaskdb
  POSTGRES_USER: flaskuser
  HOST: postgres
  DBNAME: flaskdb
  USER: flaskuser
  PORT: "5432"
