apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  # You should create this value with `echo -n 'your-password' | base64`
  POSTGRES_PASSWORD: c2VjcmV0LXBhc3N3b3Jk
  PASSWORD: c2VjcmV0LXBhc3N3b3Jk
  CLIENT_SECRET: RmRYVDRCTkp6dFo1emU1V2F3UWg0SzdCQ3g3R2RjQk4=
  SECRET_KEY: UzA0allWSTNjVEZ1WVRKdVdHNDRRemRFUnpCNWRESkdNbUUyZFVWc2JrVUtzCg==
